### ISSUE TITLE
panic on getPubKeyFromEnv

### ISSUE THREAD

**Issue by eumel8** [eumel8/cosignwebhook#26]
cosignwebhook:3.2.0

cosignwebhook crash in getPubKeyFromEnv:

```
2023/11/06 08:06:30 http: panic serving 10.42.0.0:8578: runtime error: invalid memory address or nil pointer derefere
nce
goroutine 10112 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ce8a00?, 0x326cae0?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
main.(*CosignServerHandler).getPubKeyFromEnv(0xc000656000?, 0xc000ba0900)
        /app/cosignwebhook.go:110 +0xa1
main.(*CosignServerHandler).serve(0xc0004bc870?, {0x22dc190, 0xc0009280e0}, 0xc00027aa00?)
        /app/cosignwebhook.go:183 +0x366
net/http.HandlerFunc.ServeHTTP(0x10?, {0x22dc190?, 0xc0009280e0?}, 0xc0003b23ec?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0x410725?, {0x22dc190, 0xc0009280e0}, 0xc00027aa00)
        /usr/local/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0x22d14e0?}, {0x22dc190?, 0xc0009280e0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000967290, {0x22e9a58, 0xc00062e270})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 13
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
```

The last validated Pod comes from a Job and has no Env var and no secret.

cc: @puffitos

**Comment by puffitos** [comment]
Don't panic it's organic! I'll take a look tomorrow 👌
